### ISSUE TITLE
Question about `sendAllFiles`

### ISSUE THREAD

**Issue by raymondben** [INWTlab/rsync#12]
A question - what was the reason for changing `src <- getSrc(db)` to `src <- paste0(getSrc(db), "*")` on https://github.com/INWTlab/rsync/blob/master/R/sendAllFiles.R#L16? The associated commit message (https://github.com/INWTlab/rsync/commit/45ae7fe163497d6b7d1719fea861587ac7599dab#diff-251fdcbecd04c3bd9b7a852bdf4fa775da3b7ca2538943bcabf4baa92fe6acab) just says "fix for rsync compatibility error".

I ask because `src <- paste0(getSrc(db), "*")` won't match files named e.g. `.something`. For example:
```
> con <- setupTestEnvironment()
> invisible(removeAllFiles(con))
> cat("blah", file = file.path(getSrc(con), ".dotfile"))
> sendAllFiles(con)
Rsync server: 
  src: /tmp/Rtmpjxgkt8/fikwbsucyg/
  dest: /tmp/Rtmpjxgkt8/dhvaurxgjb/ 
Directory in destination:
[1] " rsync     /tmp/Rtmpjxgkt8/dhvaurxgjb/"
            name        lastModified size
1        x.Rdata 2021-12-03 10:46:11   69
2        y.Rdata 2021-12-03 10:46:11   68
3 nested  folder 2021-12-03 10:46:11 4096
4  nested folder 2021-12-03 10:46:11 4096
5   nestedFolder 2021-12-03 10:46:11 4096
```
The `.dotfile` doesn't get transferred. Removing the '*' solves it, but must introduce some other problem otherwise you wouldn't have made that change in the first place.

```
> sessionInfo()
R version 4.0.5 (2021-03-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.3 LTS
```

**Comment by wahani** [comment]
If I recall correctly: This was an issue with an older rsync version in which `folder/` as source would create `dest/folder`, instead of adding the contents of `folder` into `dest`. At the time I tried to reproduce it inside a docker container, to have a test for this but failed.

I agree that we should be able to sync hidden files with `sendAllFiles`. I think what we should do is to use `paste0(getSrc(db), ".")` which should resolve to *all* files in `src`. Hopefully also in that older version of rsync.

As a workaround you can also use:

```
rsync::sendFile(con, ".")
```

**Comment by raymondben** [comment]
Ah, thanks @wahani - that makes sense. Using "." works for me (didn't think of trying that!). Closing this - I have a suggestion for an additional feature that I'll send in a PR.
