### ISSUE TITLE
Connecting via ssh

### ISSUE THREAD

**Issue by hrbrmstr** [INWTlab/rsync#4]
All the examples I've seen and the attempts I've made to try to use this package in a secure fashion (e.g. ssh-rsync) indicate there not even a remote attempt at supporting secure rsync.

This puts users of this package at significant risk (yes, even on an internal LAN).

**Comment by wahani** [comment]
Thanks for bringing this up. There are different options for remote connections
with rsync. From the docs:

> There are two different ways for rsync to contact a remote system: using a
> remote-shell program as the transport (such as ssh or rsh) or contacting an
> rsync daemon directly via TCP. The remote-shell transport is used whenever the
> source or destination path contains a single colon (:) separator after a host
> specification. Contacting an rsync daemon directly happens when the source or
> destination path contains a double colon (::) separator after a host
> specification, OR when an rsync:// URL is specified (see also the "USING
> RSYNC-DAEMON FEATURES VIA A REMOTE-SHELL CONNECTION" section for an exception to
> this latter rule).

> Once installed, you can use rsync to any machine that you can access via a
> remote shell (as well as some that you can access using the rsync daemon-mode
> protocol). For remote transfers, a modern rsync uses ssh for its communications,
> but it may have been configured to use a different remote shell by default, such
> as rsh or remsh.

So if you tried to configure rsync to use a particular remote-shell using the -e
option, this is not supported right know. However, `ssh` is the default. So if
you want to use rsync to send or receive files from a remote location via SSH,
you have to configure your [ssh profiles](https://www.ssh.com/ssh/config/). Once
you have a configuration, e.g. for `my-remote-machine`, you can use something along
the lines of:

```
rsync local-folder my-remote-machine:~/remote-folder
```

and ssh will be used. It makes sense to put a link how to do that into the
documentation. Currently what you can do is to set an environment variable:

> You can also specify any remote shell you like, either by using the -e command
> line option, or by setting the RSYNC_RSH environment variable.

The other option for remote connection is to contact a rsync-daemon directly.
E.g. when we use `rsync://` in the dest. In that case TCP would be used. To use
SSH in this scenario the 'USING RSYNC-DAEMON FEATURES VIA A REMOTE-SHELL
CONNECTION' section requires you to establish a connections via SSH forwarding
and whitelisting only localhost on the remote rsync-daemon (the configuration
provides IP-whitelisting). This would need to happen outside of this package and
would be part of the rsyncd configuration. Setting up a rsync daemon without SSH
is probably only an option inside a trusted intranet.

To move forward:

- Add -e for custom configuration. On the command line you may specify options
  for ssh itself but I would prefer to encourage the use of configuration files.
- Add the option to use a config file instead of the environment variable when
  connecting to a remote rsync daemon. This would replace what we currently do
  with the password.

If this does not cover your use-case, it would be helpful if you can give more
detail on what you were trying to do and what you think the package should provide 
to help.

**Comment by hrbrmstr** [comment]
I'm kind of an expert on `rsync`, contributed to the development of this blog post — https://blog.rapid7.com/2018/12/21/rsunk-your-battleship-an-ocean-of-data-exposed-through-rsync/  (I'm head of data science at Rapid7) — and regularly find horribly exposed rsync endpoints all over the internet (which is what your package is going to help increase) so thx for for man page paste, but that's not what the problem is.

You *encourage* horribly insecure use of rsync and don't support the most basic/fundamental source or target rsync endpoint specification (`user@host:/path`). You don't document how to help users use this securely and are putting their data at significant risk in transit and even at the remote endpoint  itself given the default/expected non-SSH-wrapped usage.

I can't stop you from harming others but this package will indeed cause harm if it's used (something I've tried to actively discourage publicly until the default behavior relies on secure rsync comms). Please seriously consider refactoring it to require SSH-wrapped rsync sessions and not support plaintext (even with a password since MD4 hashed passwords might as well be plaintext).

**Comment by wahani** [comment]
I will close this issue. We added SSH support a while ago and there seem to be no recent issues with it.
